### PR TITLE
added a footer to index.html

### PR DESCRIPTION
**Pull request by thatweirdcoder**
Added a footer with the twitter, github, itunes, and rss links to make it look prettier. :D

### CODE REVIEW

**Comment by thatweirdcoder** [comment]
Can't add the assets that should be used. Here is a link with them https://www.dropbox.com/sh/44hb36kr7a0klth/AACbQo04_CojTpHrv09eZXK9a?dl=0

**Comment by samwho** [comment]
Hey! I replied on Twitter but should probably reply here as well. The assets you've chosen stand out a little too much on the page. Could you give the http://fontawesome.io/icons/ a try instead?

Thanks so much for working on this. :)

**Review by thatweirdcoder — COMMENTED** [review]
Used fontawesome, :D still need to add the directory. Dropbox link: https://www.dropbox.com/sh/ctxlw6famxpfvrg/AACY9uNRlFk4oCZ7rLgdBvnga?dl=0

**Comment by lethargilistic** [comment]
OK, I hacked on this a bit and merged it directly. Unfortunately, I wasn't able to do it through this page, so I'm going to close this instead of merging it. But you're definitely a contributor now! Thanks a lot and congrats~!

Same for #9

**Pull request closed without merging**
